version: "3.2"
services:
  db:
    image: postgres:12.3-alpine
    container_name: heroku-go-embed-template-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: heroku-go-embed-template_db
    ports:
      - 5444:5432
